[build]
  base = "runetrack-2.0/client"
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
