services:
  - type: web
    name: runetrack-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: ATLAS_URI
        sync: false
      - key: PORT
        value: 5050
